import { theme } from "pgv-lib/ui/themes"
import { MenuResponseType } from "../types/MenuResponseTypes"

export const MenuServicesMock: MenuResponseType = {
  modules: [
    {
      title: "Suíte",
      description:
        "Crie cadastros com todos os seus atributos em boa parte do <strong>ERP Voalle</strong>.",
      segment: "cadastros",
      slug: "suite_cadastros",
      icon: "VoallePgv",
      iconColor: theme.palette.accent.suite,
      path: "",
      isExternalMenu: true,
    },
    {
      title: "Finee",
      description: "Techfin com foco em tecnologias de cobranças.",
      segment: "cadastros",
      slug: "finee_cadastros",
      icon: "FineePgv",
      iconColor: theme.palette.accent.finee,
      path: "",
      isExternalMenu: true,
    },
    {
      title: "Projetos",
      description:
        "Práticas <strong>PMI</strong> e <strong>SCRUM</strong>: alcance seus objetivos.",
      segment: "cadastros",
      slug: "projects_cadastros",
      icon: "TableChartViewPgv",
      iconColor: theme.palette.accent.projects,
      path: "",
      isExternalMenu: true,
    },
    {
      title: "CRM",
      description:
        "<strong>Customer Relationship Management</strong> ou Gestão de Vendas da Empresa.",
      segment: "cadastros",
      slug: "crm_cadastros",
      icon: "RadarPgv",
      iconColor: theme.palette.accent.crm,
      path: "",
      isExternalMenu: true,
    },
    {
      title: "CRM V3",
      description:
        "<strong>Customer Relationship Management</strong> ou Gestão de Vendas da Empresa.",
      segment: "cadastros",
      slug: "crm_cadastros",
      icon: "RadarPgv",
      iconColor: theme.palette.accent.crm,
      path: "crm/registrations?menuId=1#registrations",
      isExternalMenu: false,
    },
    {
      title: "Service Desk",
      description:
        "Centralize os atendimentos de suporte com clientes internos e externos.",
      segment: "cadastros",
      slug: "serviceDesk_cadastros",
      icon: "HeadsetMicOutlined",
      iconColor: theme.palette.accent.serviceDesk,
      path: "",
      isExternalMenu: true,
    },
    {
      title: "Estratégia",
      description:
        "Visão intuitiva do planejamento financeiro, Clientes e Processos.",
      segment: "cadastros",
      slug: "strategy_cadastros",
      icon: "RebasePgv",
      iconColor: theme.palette.accent.strategy,
      path: "",
      isExternalMenu: true,
    },
    {
      title: "Faturamento",
      description:
        "Gerencie contratos com emissões de notas fiscais das prestações de serviços.",
      segment: "cadastros",
      slug: "billing_cadastros",
      icon: "PriceCheck",
      iconColor: theme.palette.accent.billing,
      path: "",
      isExternalMenu: true,
    },
    {
      title: "Materiais",
      description:
        "Controle de estoque: item, entrada, venda, movimentação e histórico.",
      segment: "cadastros",
      slug: "materials_cadastros",
      icon: "InventoryPgv",
      iconColor: theme.palette.accent.materials,
      path: "",
      isExternalMenu: true,
    },
    {
      title: "Inovação",
      description:
        "<strong>Abra Inovação</strong> através de ideias, processos e pesquisas abertas.",
      segment: "cadastros",
      slug: "innovation_cadastros",
      icon: "EmojiObjectsOutlined",
      iconColor: theme.palette.accent.innovation,
      path: "",
      isExternalMenu: true,
    },
    {
      title: "Financeiro",
      description: "Tenha toda a gestão do financeiro de sua empresa.",
      segment: "cadastros",
      slug: "financial_cadastros",
      icon: "InsertChartOutlined",
      iconColor: theme.palette.accent.financial,
      path: "",
      isExternalMenu: true,
    },
    {
      title: "ISP - Telecom",
      description:
        "Rotinas que fazem parte da gestão do provedor de internet e telefonia.",
      segment: "cadastros",
      slug: "ispTelecom_cadastros",
      icon: "RouterOutlined",
      iconColor: theme.palette.accent.ispTelecom,
      path: "",
      isExternalMenu: true,
    },
    {
      title: "Suíte",
      description:
        "Gerencie todos os seus atributos em boa parte do <strong>ERP Voalle</strong>.",
      segment: "operacoes",
      slug: "suite_operacoes",
      icon: "VoallePgv",
      iconColor: theme.palette.accent.suite,
      path: "",
      isExternalMenu: true,
    },
    {
      title: "ISP - Telecom",
      description:
        "Rotinas que fazem parte da gestão do provedor de internet e telefonia.",
      segment: "operacoes",
      slug: "ispTelecom_operacoes",
      icon: "RouterOutlined",
      iconColor: theme.palette.accent.ispTelecom,
      path: "",
      isExternalMenu: true,
    },
  ],
  values: [
    {
      title: "Pessoas - Completo",
      moduleSlug: "suite_cadastros",
      path: "people",
      isExternalMenu: true,
    },
    {
      title: "Pessoas - Simplificado",
      moduleSlug: "suite_cadastros",
      path: "people_simplified",
      isExternalMenu: true,
    },
    {
      title: "Grupos Econômicos",
      moduleSlug: "suite_cadastros",
      path: "business_groups",
      isExternalMenu: true,
    },
    {
      title: "Grupos de Pessoas",
      moduleSlug: "suite_cadastros",
      path: "people_groups",
      isExternalMenu: true,
    },
    {
      title: "Setores de Atuação",
      moduleSlug: "suite_cadastros",
      path: "industry_sectors",
      isExternalMenu: true,
    },
    {
      title: "Atividades Econômicas",
      moduleSlug: "suite_cadastros",
      path: "activities",
      isExternalMenu: true,
    },
    {
      title: "Regiões",
      moduleSlug: "suite_cadastros",
      path: "regions",
      isExternalMenu: true,
    },
    {
      title: "Rotas",
      moduleSlug: "suite_cadastros",
      path: "routes",
      isExternalMenu: true,
    },
    {
      title: "Cargos Ocupacionais",
      moduleSlug: "suite_cadastros",
      path: "crm_functions",
      isExternalMenu: true,
    },
    {
      title: "Unidades de Medida",
      moduleSlug: "suite_cadastros",
      path: "units_measures",
      isExternalMenu: true,
    },
    {
      title: "Locais",
      moduleSlug: "suite_cadastros",
      path: "companies_places",
      isExternalMenu: true,
    },
    {
      title: "Áreas",
      moduleSlug: "suite_cadastros",
      path: "sector_areas",
      isExternalMenu: true,
    },
    {
      title: "Equipes",
      moduleSlug: "suite_cadastros",
      path: "teams",
      isExternalMenu: true,
    },
    {
      title: "Mensagens Padrão",
      moduleSlug: "suite_cadastros",
      path: "messages",
      isExternalMenu: true,
    },
    {
      title: "Modelos de E-mail",
      moduleSlug: "suite_cadastros",
      path: "email_models",
      isExternalMenu: true,
    },
    {
      title: "Tipos de Documento",
      moduleSlug: "suite_cadastros",
      path: "documentation_types",
      isExternalMenu: true,
    },
    {
      title: "Processos - Mapeamento",
      moduleSlug: "suite_cadastros",
      path: "assignment_models",
      isExternalMenu: true,
    },
    {
      title: "Feriados",
      moduleSlug: "suite_cadastros",
      path: "holidays",
      isExternalMenu: true,
    },
    {
      title: "Templates Impressão",
      moduleSlug: "suite_cadastros",
      path: "print_templates",
      isExternalMenu: true,
    },
    {
      title: "Serviços de E-mail",
      moduleSlug: "suite_cadastros",
      path: "email_services",
      isExternalMenu: true,
    },
    {
      title: "Atividades Internas - Tipos",
      moduleSlug: "suite_cadastros",
      path: "assignment_internal_types",
      isExternalMenu: true,
    },
    {
      title: "Formas de Contato",
      moduleSlug: "suite_cadastros",
      path: "contact_forms",
      isExternalMenu: true,
    },
    {
      title: "Motivos de Contato",
      moduleSlug: "suite_cadastros",
      path: "contact_motives",
      isExternalMenu: true,
    },
    {
      title: "Municípios",
      moduleSlug: "suite_cadastros",
      path: "code_cities",
      isExternalMenu: true,
    },
    {
      title: "Assinatura Eletrônica de Documentos",
      moduleSlug: "suite_cadastros",
      path: "electronic_signatures",
      isExternalMenu: true,
    },
    {
      title: "Formulário Dinâmico",
      moduleSlug: "suite_cadastros",
      path: "individual_forms",
      isExternalMenu: true,
    },
    {
      title: "Atalhos - Aplicativo/Portal",
      moduleSlug: "suite_cadastros",
      path: "shortcuts",
      isExternalMenu: true,
    },
    {
      title: "Insígnias",
      moduleSlug: "suite_cadastros",
      path: "insignias",
      isExternalMenu: true,
    },
    {
      title: "Minhas Tarefas",
      moduleSlug: "suite_operacoes",
      path: "assignments",
      isExternalMenu: true,
    },
    {
      title: "Tarefas Solicitadas",
      moduleSlug: "suite_operacoes",
      path: "requested_tasks",
      isExternalMenu: true,
    },
    {
      title: "Tarefas Encerradas",
      moduleSlug: "suite_operacoes",
      path: "executed_tasks",
      isExternalMenu: true,
    },
    {
      title: "Ata de Reunião",
      moduleSlug: "suite_operacoes",
      path: "conferences",
      isExternalMenu: true,
    },
    {
      title: "Comunicações Internas",
      moduleSlug: "suite_operacoes",
      path: "communications",
      isExternalMenu: true,
    },
    {
      title: "Mensagens Cliente",
      moduleSlug: "suite_operacoes",
      path: "messages_people",
      isExternalMenu: true,
    },
    {
      title: "Documentações a Vencer",
      moduleSlug: "suite_operacoes",
      path: "overdue_documents",
      isExternalMenu: true,
    },
    {
      title: "Solicitação de Recurso",
      moduleSlug: "suite_operacoes",
      path: "resource_requests",
      isExternalMenu: true,
    },
    {
      title: "Aprovação de Recurso",
      moduleSlug: "suite_operacoes",
      path: "approbation_resource_requests",
      isExternalMenu: true,
    },
    {
      title: "Processos",
      moduleSlug: "suite_operacoes",
      path: "internal_processes",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Comunicações",
      moduleSlug: "suite_operacoes",
      path: "communication_dashboard",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Aplicativos Móveis",
      moduleSlug: "suite_operacoes",
      path: "mobile",
      isExternalMenu: true,
    },
    {
      title: "Tarefas em Aberto",
      moduleSlug: "suite_relatorios",
      path: "javascript:open_tasks_filter();",
      isExternalMenu: true,
    },
    {
      title: "Tarefas Executadas",
      moduleSlug: "suite_relatorios",
      path: "javascript:performed_tasks_filter();",
      isExternalMenu: true,
    },
    {
      title: "Exportador de Dados - Relat. Cadastrados",
      moduleSlug: "suite_relatorios",
      path: "customized_reports_models",
      isExternalMenu: true,
    },
    {
      title: "Atividades - Em Andamento",
      moduleSlug: "suite_analises",
      path: "open_assignments",
      isExternalMenu: true,
    },
    {
      title: "Tarefas Executadas",
      moduleSlug: "suite_analises",
      path: "performed_tasks",
      isExternalMenu: true,
    },
    {
      title: "Melhores Qualificações",
      moduleSlug: "suite_analises",
      path: "best_qualifications",
      isExternalMenu: true,
    },
    {
      title: "Busca Avançada",
      moduleSlug: "suite_analises",
      path: "advanced_searches",
      isExternalMenu: true,
    },
    {
      title: "Anexos",
      moduleSlug: "suite_analises",
      path: "attachments",
      isExternalMenu: true,
    },
    {
      title: "Pessoas",
      moduleSlug: "suite_analises",
      path: "people_consults",
      isExternalMenu: true,
    },
    {
      title: "Atas Executadas",
      moduleSlug: "suite_analises",
      path: "conferences/all",
      isExternalMenu: true,
    },
    {
      title: "Mapa Alocação de Recursos",
      moduleSlug: "suite_analises",
      path: "allocation_maps",
      isExternalMenu: true,
    },
    {
      title: "Auditoria - Logs",
      moduleSlug: "suite_analises",
      path: "user_interaction_logs",
      isExternalMenu: true,
    },
    {
      title: "SMS Enviados",
      moduleSlug: "suite_analises",
      path: "sms_logs",
      isExternalMenu: true,
    },
    {
      title: "Suíte - Reativar Pessoas",
      moduleSlug: "suite_utilitarios",
      path: "people_deactivated",
      isExternalMenu: true,
    },
    {
      title: "Suíte - Inativar Pessoas ",
      moduleSlug: "suite_utilitarios",
      path: "people_status",
      isExternalMenu: true,
    },
    {
      title: "Suíte - Agendar Processo",
      moduleSlug: "suite_utilitarios",
      path: "company_assignment_models",
      isExternalMenu: true,
    },
    {
      title: "Suíte - Log de Acesso",
      moduleSlug: "suite_utilitarios",
      path: "logs",
      isExternalMenu: true,
    },
    {
      title: "Tarefas - Manutenção",
      moduleSlug: "suite_utilitarios",
      path: "maintenance_tasks",
      isExternalMenu: true,
    },
    {
      title: "Portal - Usuários",
      moduleSlug: "suite_utilitarios",
      path: "person_users",
      isExternalMenu: true,
    },
    {
      title: "Portal - Contato/Usuário",
      moduleSlug: "suite_utilitarios",
      path: "generate_contacts_users",
      isExternalMenu: true,
    },
    {
      title: "Portal - Cadastro em lote",
      moduleSlug: "suite_utilitarios",
      path: "bulk_person_users",
      isExternalMenu: true,
    },
    {
      title: "Portal - Enviar E-mail",
      moduleSlug: "suite_utilitarios",
      path: "generate_email_contacts_users",
      isExternalMenu: true,
    },
    {
      title: "Equipes - Manutenção",
      moduleSlug: "suite_utilitarios",
      path: "maintenance_teams",
      isExternalMenu: true,
    },
    {
      title: "Exportador de Dados",
      moduleSlug: "suite_utilitarios",
      path: "customized_reports",
      isExternalMenu: true,
    },
    {
      title: "Base de Conhecimento",
      moduleSlug: "suite_utilitarios",
      path: "synbook/documentation_articles",
      isExternalMenu: true,
    },
    {
      title: "Auditoria - Configurações",
      moduleSlug: "suite_utilitarios",
      path: "user_interaction_logs_configurations",
      isExternalMenu: true,
    },
    {
      title: "Comunicados",
      moduleSlug: "suite_utilitarios",
      path: "people_communications",
      isExternalMenu: true,
    },
    {
      title: "Perspectiva",
      moduleSlug: "estrategia_cadastros",
      path: "perspectives",
      isExternalMenu: true,
    },
    {
      title: "Aspectos",
      moduleSlug: "estrategia_cadastros",
      path: "aspects",
      isExternalMenu: true,
    },
    {
      title: "Itens de Aspectos",
      moduleSlug: "estrategia_cadastros",
      path: "aspect_items",
      isExternalMenu: true,
    },
    {
      title: "Fator Crítico Sucesso",
      moduleSlug: "estrategia_cadastros",
      path: "critical_success_factors",
      isExternalMenu: true,
    },
    {
      title: "Gestão",
      moduleSlug: "estrategia_cadastros",
      path: "managements/index_g",
      isExternalMenu: true,
    },
    {
      title: "Planejamento Estratégico",
      moduleSlug: "estrategia_operacoes",
      path: "plannings",
      isExternalMenu: true,
    },
    {
      title: "Planejamento Estratégico",
      moduleSlug: "estrategia_analises",
      path: "planning_views",
      isExternalMenu: true,
    },
    {
      title: "Meus Indicadores",
      moduleSlug: "estrategia_indicadores",
      path: "indicators",
      isExternalMenu: true,
    },
    {
      title: "Painel de Indicadores",
      moduleSlug: "estrategia_indicadores",
      path: "indicators/panel",
      isExternalMenu: true,
    },
    {
      title: "Manutenção de Indicadores",
      moduleSlug: "estrategia_indicadores",
      path: "indicator_tree",
      isExternalMenu: true,
    },
    {
      title: "Ata de Reunião",
      moduleSlug: "estrategia_indicadores",
      path: "conferences/index/2",
      isExternalMenu: true,
    },
    {
      title: "Itens Termo de Abertura",
      moduleSlug: "projetos_cadastros",
      path: "project_opening_statement_items",
      isExternalMenu: true,
    },
    {
      title: "Portfólios",
      moduleSlug: "projetos_cadastros",
      path: "project_portfolios",
      isExternalMenu: true,
    },
    {
      title: "Programas",
      moduleSlug: "projetos_cadastros",
      path: "project_programs",
      isExternalMenu: true,
    },
    {
      title: "Naturezas Financeiras",
      moduleSlug: "projetos_cadastros",
      path: "financers_natures",
      isExternalMenu: true,
    },
    {
      title: "Modelos de Projetos",
      moduleSlug: "projetos_operacoes",
      path: "project_models",
      isExternalMenu: true,
    },
    {
      title: "Pré-Projetos",
      moduleSlug: "projetos_operacoes",
      path: "projects/preProject",
      isExternalMenu: true,
    },
    {
      title: "Meus Projetos",
      moduleSlug: "projetos_operacoes",
      path: "projects",
      isExternalMenu: true,
    },
    {
      title: "Projetos Suspensos",
      moduleSlug: "projetos_operacoes",
      path: "projects/suspend",
      isExternalMenu: true,
    },
    {
      title: "Geral",
      moduleSlug: "projetos_relatorios",
      path: "javascript:getProjectsReport();",
      isExternalMenu: true,
    },
    {
      title: "Por Portfólio",
      moduleSlug: "projetos_relatorios",
      path: "javascript:getProjectsByPortfolioReport();",
      isExternalMenu: true,
    },
    {
      title: "Por Programa",
      moduleSlug: "projetos_relatorios",
      path: "javascript:getProjectsByProgramReport();",
      isExternalMenu: true,
    },
    {
      title: "Recursos - Pessoas",
      moduleSlug: "projetos_analises",
      path: "project_people_analysis",
      isExternalMenu: true,
    },
    {
      title: "Projetos em Andamento",
      moduleSlug: "projetos_analises",
      path: "project_general_view_analysis",
      isExternalMenu: true,
    },
    {
      title: "Projetos Concluídos",
      moduleSlug: "projetos_analises",
      path: "projects/completed",
      isExternalMenu: true,
    },
    {
      title: "Projetos Cancelados",
      moduleSlug: "projetos_analises",
      path: "projects/canceled",
      isExternalMenu: true,
    },
    {
      title: "Temáticas",
      moduleSlug: "inovacao_cadastros",
      path: "idea_groups",
      isExternalMenu: true,
    },
    {
      title: "Formulários de Ideias",
      moduleSlug: "inovacao_cadastros",
      path: "idea_forms",
      isExternalMenu: true,
    },
    {
      title: "Critérios de Avaliação",
      moduleSlug: "inovacao_cadastros",
      path: "idea_evaluation_criterias",
      isExternalMenu: true,
    },
    {
      title: "Grupos de Colaboração",
      moduleSlug: "inovacao_cadastros",
      path: "idea_colaboration_groups",
      isExternalMenu: true,
    },
    {
      title: "Comitês de Avaliação",
      moduleSlug: "inovacao_cadastros",
      path: "idea_evaluation_committees",
      isExternalMenu: true,
    },
    {
      title: "Tipos para Ideias",
      moduleSlug: "inovacao_cadastros",
      path: "idea_types",
      isExternalMenu: true,
    },
    {
      title: "Painel de Ideias",
      moduleSlug: "inovacao_operacoes",
      path: "ideas",
      isExternalMenu: true,
    },
    {
      title: "Painel de Avaliação",
      moduleSlug: "inovacao_operacoes",
      path: "ideas/evaluation_list",
      isExternalMenu: true,
    },
    {
      title: "Ideias Aprovadas",
      moduleSlug: "inovacao_operacoes",
      path: "ideas/approved_list",
      isExternalMenu: true,
    },
    {
      title: "Ideias Arquivadas",
      moduleSlug: "inovacao_operacoes",
      path: "ideas/archived_list",
      isExternalMenu: true,
    },
    {
      title: "Ranking de Ideias",
      moduleSlug: "inovacao_analises",
      path: "idea_informations",
      isExternalMenu: true,
    },
    {
      title: "Ranking de Colaborações",
      moduleSlug: "inovacao_analises",
      path: "idea_informations/collaborations",
      isExternalMenu: true,
    },
    {
      title: "Catálogo de Serviços",
      moduleSlug: "service_desk_cadastros",
      path: "catalog_services",
      isExternalMenu: true,
    },
    {
      title: "Itens de Serviço",
      moduleSlug: "service_desk_cadastros",
      path: "catalog_services_items",
      isExternalMenu: true,
    },
    {
      title: "Subitens de Serviço",
      moduleSlug: "service_desk_cadastros",
      path: "catalog_service_item_classes",
      isExternalMenu: true,
    },
    {
      title: "Status de Solicitações",
      moduleSlug: "service_desk_cadastros",
      path: "incident_status",
      isExternalMenu: true,
    },
    {
      title: "Situações de Solicitações",
      moduleSlug: "service_desk_cadastros",
      path: "service_level_agreements",
      isExternalMenu: true,
    },
    {
      title: "Solicitações - Tipos",
      moduleSlug: "service_desk_cadastros",
      path: "incident_types",
      isExternalMenu: true,
    },
    {
      title: "Motivos de Solicitações",
      moduleSlug: "service_desk_cadastros",
      path: "solicitation_routing_motives",
      isExternalMenu: true,
    },
    {
      title: "Solicitações - Contextos",
      moduleSlug: "service_desk_cadastros",
      path: "solicitation_classifications",
      isExternalMenu: true,
    },
    {
      title: "Solicitações - Problemas",
      moduleSlug: "service_desk_cadastros",
      path: "solicitation_problems",
      isExternalMenu: true,
    },
    {
      title: "Contratos - Tipos",
      moduleSlug: "service_desk_cadastros",
      path: "contract_types",
      isExternalMenu: true,
    },
    {
      title: "Evento Padrão",
      moduleSlug: "service_desk_cadastros",
      path: "contract_event_types",
      isExternalMenu: true,
    },
    {
      title: "Configuração de Roteirização Field Service",
      moduleSlug: "service_desk_cadastros",
      path: "fsm_routing_configs",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Gerente",
      moduleSlug: "service_desk_operacoes",
      path: "service_dashboard",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Atendente",
      moduleSlug: "service_desk_operacoes",
      path: "service_personal_dashboard",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Contratos",
      moduleSlug: "service_desk_operacoes",
      path: "contract_dashboard",
      isExternalMenu: true,
    },
    {
      title: "Central de Serviços",
      moduleSlug: "service_desk_operacoes",
      path: "service_center",
      isExternalMenu: true,
    },
    {
      title: "Solicitações - em Aberto",
      moduleSlug: "service_desk_operacoes",
      path: "open_solicitations",
      isExternalMenu: true,
    },
    {
      title: "Solicitações - Feedbacks",
      moduleSlug: "service_desk_operacoes",
      path: "solicitation_feedbacks",
      isExternalMenu: true,
    },
    {
      title: "Solicitações - Validações",
      moduleSlug: "service_desk_operacoes",
      path: "solicitation_validations",
      isExternalMenu: true,
    },
    {
      title: "Versionamento",
      moduleSlug: "service_desk_operacoes",
      path: "versions",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Parâmetros do Atendimento",
      moduleSlug: "service_desk_operacoes",
      path: "dashboard_assignment_parameters",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Monitoramento de Técnicos",
      moduleSlug: "service_desk_operacoes",
      path: "technician_tracking",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - MVNO",
      moduleSlug: "service_desk_operacoes",
      path: "dashboard_mvno",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Field Service",
      moduleSlug: "service_desk_operacoes",
      path: "managers_dashboard",
      isExternalMenu: true,
    },
    {
      title: "Solicitações de Parceiros",
      moduleSlug: "service_desk_operacoes",
      path: "sale_partner_solicitations",
      isExternalMenu: true,
    },
    {
      title: "Técnico - Solicitações",
      moduleSlug: "service_desk_relatorios",
      path: "javascript:getReportByTechnical();",
      isExternalMenu: true,
    },
    {
      title: "Técnico - Comparativo",
      moduleSlug: "service_desk_relatorios",
      path: "javascript:treatment_analysis();",
      isExternalMenu: true,
    },
    {
      title: "Técnico - SLA",
      moduleSlug: "service_desk_relatorios",
      path: "javascript:reportTreatmentSLA();",
      isExternalMenu: true,
    },
    {
      title: "Cliente - Solicitações",
      moduleSlug: "service_desk_relatorios",
      path: "javascript:getReportByClient();",
      isExternalMenu: true,
    },
    {
      title: "Cliente - Comparativo",
      moduleSlug: "service_desk_relatorios",
      path: "javascript:reportClientAnalysis();",
      isExternalMenu: true,
    },
    {
      title: "Cliente - SLA",
      moduleSlug: "service_desk_relatorios",
      path: "javascript:reportClientSLA();",
      isExternalMenu: true,
    },
    {
      title: "Cliente - Extrato",
      moduleSlug: "service_desk_relatorios",
      path: "javascript:extract_drive_client();",
      isExternalMenu: true,
    },
    {
      title: "Cliente - Contratos e Catálogos",
      moduleSlug: "service_desk_relatorios",
      path: "javascript:getReportByClientContractsAndServices();",
      isExternalMenu: true,
    },
    {
      title: "Serviço - Curva ABC",
      moduleSlug: "service_desk_relatorios",
      path: "javascript:getServiceCurve();",
      isExternalMenu: true,
    },
    {
      title: "Solicitações por área",
      moduleSlug: "service_desk_relatorios",
      path: "javascript:record_by_sector_area_filter();",
      isExternalMenu: true,
    },
    {
      title: "Solicitações - Em Andamento",
      moduleSlug: "service_desk_analises",
      path: "assignment_incident_analysis",
      isExternalMenu: true,
    },
    {
      title: "Solicitações - Gerencial",
      moduleSlug: "service_desk_analises",
      path: "service_managerial",
      isExternalMenu: true,
    },
    {
      title: "Solicitações - Listagem",
      moduleSlug: "service_desk_analises",
      path: "all_solicitations",
      isExternalMenu: true,
    },
    {
      title: "Solicitações - Visão Geral",
      moduleSlug: "service_desk_analises",
      path: "solicitations_managerial",
      isExternalMenu: true,
    },
    {
      title: "Solicitações - Tempo Permanência",
      moduleSlug: "service_desk_analises",
      path: "assignment_solicitation_permanencies",
      isExternalMenu: true,
    },
    {
      title: "Solicitações - Encaminhamentos",
      moduleSlug: "service_desk_analises",
      path: "solicitation_actions_analysis",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Produtividade",
      moduleSlug: "service_desk_analises",
      path: "productivity/productivity_dashboard",
      isExternalMenu: true,
    },
    {
      title: "Contratos - Custo Atendimento",
      moduleSlug: "service_desk_analises",
      path: "hours_of_service_analysis",
      isExternalMenu: true,
    },
    {
      title: "Contratos - Eventos",
      moduleSlug: "service_desk_analises",
      path: "contract_event_analysis",
      isExternalMenu: true,
    },
    {
      title: "Operações por Cliente",
      moduleSlug: "service_desk_analises",
      path: "service_people_consults",
      isExternalMenu: true,
    },
    {
      title: "Operações por Contrato",
      moduleSlug: "service_desk_analises",
      path: "contract_consults",
      isExternalMenu: true,
    },
    {
      title: "Operações por Etiquetas",
      moduleSlug: "service_desk_analises",
      path: "contract_service_tag_consults",
      isExternalMenu: true,
    },
    {
      title: "Atendimentos Cfe Catálogo",
      moduleSlug: "service_desk_analises",
      path: "catalog_service_analysis",
      isExternalMenu: true,
    },
    {
      title: "Objetos - Romaneio Interno",
      moduleSlug: "service_desk_analises",
      path: "internal_packing_lists",
      isExternalMenu: true,
    },
    {
      title: "Objetos - Romaneio Cliente",
      moduleSlug: "service_desk_analises",
      path: "client_packing_lists",
      isExternalMenu: true,
    },
    {
      title: "Listagem de Ligações",
      moduleSlug: "service_desk_analises",
      path: "pbx_calls",
      isExternalMenu: true,
    },
    {
      title: "Solicitação - Manutenção",
      moduleSlug: "service_desk_utilitarios",
      path: "maintenance_incidents",
      isExternalMenu: true,
    },
    {
      title: "Solicitação - Agendamento",
      moduleSlug: "service_desk_utilitarios",
      path: "service_solicitation_schedules",
      isExternalMenu: true,
    },
    {
      title: "Solicitação - Classificação",
      moduleSlug: "service_desk_utilitarios",
      path: "classify_incidents",
      isExternalMenu: true,
    },
    {
      title: "Solicitações - Atendimento Externo",
      moduleSlug: "service_desk_utilitarios",
      path: "external_solicitations",
      isExternalMenu: true,
    },
    {
      title: "Envio Extrato Cliente",
      moduleSlug: "service_desk_utilitarios",
      path: "sending_extract_client",
      isExternalMenu: true,
    },
    {
      title: "Solicitações em Lote",
      moduleSlug: "service_desk_utilitarios",
      path: "batch_solicitations",
      isExternalMenu: true,
    },
    {
      title: "PBX - Extensões",
      moduleSlug: "service_desk_utilitarios",
      path: "pbx/extension",
      isExternalMenu: true,
    },
    {
      title: "Instituições Financeiras",
      moduleSlug: "financeiro_cadastros",
      path: "financial_institutions",
      isExternalMenu: true,
    },
    {
      title: "Contas",
      moduleSlug: "financeiro_cadastros",
      path: "accounts",
      isExternalMenu: true,
    },
    {
      title: "Naturezas Financeiras",
      moduleSlug: "financeiro_cadastros",
      path: "financers_natures",
      isExternalMenu: true,
    },
    {
      title: "DRE - Configurações",
      moduleSlug: "financeiro_cadastros",
      path: "financial_demonstration",
      isExternalMenu: true,
    },
    {
      title: "Condições de Pagamento",
      moduleSlug: "financeiro_cadastros",
      path: "payment_conditions",
      isExternalMenu: true,
    },
    {
      title: "Histórico Padrão",
      moduleSlug: "financeiro_cadastros",
      path: "financial_histories",
      isExternalMenu: true,
    },
    {
      title: "Centro de Resultado",
      moduleSlug: "financeiro_cadastros",
      path: "financial_cost_centers",
      isExternalMenu: true,
    },
    {
      title: "Tipos de Cobrança",
      moduleSlug: "financeiro_cadastros",
      path: "financial_collection_types",
      isExternalMenu: true,
    },
    {
      title: "Operações",
      moduleSlug: "financeiro_cadastros",
      path: "financial_operations",
      isExternalMenu: true,
    },
    {
      title: "Matriz Rateio Centro de Custo",
      moduleSlug: "financeiro_cadastros",
      path: "financial_matrix_divide_cost_centers",
      isExternalMenu: true,
    },
    {
      title: "Agrupadores Financeiros",
      moduleSlug: "financeiro_cadastros",
      path: "financial_groups",
      isExternalMenu: true,
    },
    {
      title: "Plano de Contas Contábeis",
      moduleSlug: "financeiro_cadastros",
      path: "company_accounting_accounts",
      isExternalMenu: true,
    },
    {
      title: "Formas de Pagamento",
      moduleSlug: "financeiro_cadastros",
      path: "payment_forms",
      isExternalMenu: true,
    },
    {
      title: "Terminais de Autoatendimento",
      moduleSlug: "financeiro_cadastros",
      path: "self_service_terminal",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Gerencial",
      moduleSlug: "financeiro_operacoes",
      path: "financial_dashboard",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Operacional",
      moduleSlug: "financeiro_operacoes",
      path: "financial_billing_dashboard",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Cobrança",
      moduleSlug: "financeiro_operacoes",
      path: "collections/collection_dashboard",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Integração Bancária",
      moduleSlug: "financeiro_operacoes",
      path: "bank_integrations/integration_dashboard",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Arquivos Magnéticos",
      moduleSlug: "financeiro_operacoes",
      path: "files_integrations",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Co-Billing",
      moduleSlug: "financeiro_operacoes",
      path: "co_billing",
      isExternalMenu: true,
    },
    {
      title: "Manutenção de Remessas Bancárias",
      moduleSlug: "financeiro_operacoes",
      path: "financial_remittance_maintenance",
      isExternalMenu: true,
    },
    {
      title: "CRE - Recbto por Cliente (Franquia)",
      moduleSlug: "financeiro_operacoes",
      path: "authentication_client_receipt_titles",
      isExternalMenu: true,
    },
    {
      title: "Geração Fatura",
      moduleSlug: "financeiro_operacoes",
      path: "financial_invoice_title_people",
      isExternalMenu: true,
    },
    {
      title: "Dashboard Recorrência",
      moduleSlug: "financeiro_operacoes",
      path: "dashboard_recurrence_contracts",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Integração Financeira",
      moduleSlug: "financeiro_operacoes",
      path: "dashboard_financial_integrations",
      isExternalMenu: true,
    },
    {
      title: "Caixa Atendimento",
      moduleSlug: "financeiro_operacoes",
      path: "cash_attendance",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Impressão",
      moduleSlug: "financeiro_operacoes",
      path: "dashboard_print_billet",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Integração de Recebíveis",
      moduleSlug: "financeiro_operacoes",
      path: "dashboard_receivable_integrations",
      isExternalMenu: true,
    },
    {
      title: "Operações com Cartão",
      moduleSlug: "financeiro_operacoes",
      path: "sent_operations",
      isExternalMenu: true,
    },
    {
      title: "Extrato Fornecedor",
      moduleSlug: "financeiro_relatorios",
      path: "javascript:search_financial_extract_supplier();",
      isExternalMenu: true,
    },
    {
      title: "Extrato Cliente",
      moduleSlug: "financeiro_relatorios",
      path: "javascript:search_financial_extract_client();",
      isExternalMenu: true,
    },
    {
      title: "Entradas/Saídas",
      moduleSlug: "financeiro_relatorios",
      path: "javascript:getFinancialMovimentationNatures();",
      isExternalMenu: true,
    },
    {
      title: "Entradas/Saídas - Por Lçto",
      moduleSlug: "financeiro_relatorios",
      path: "javascript:search_financial_movimentation_posting();",
      isExternalMenu: true,
    },
    {
      title: "CPA - Títulos em Aberto",
      moduleSlug: "financeiro_relatorios",
      path: "javascript:getFinancialPayableTitles();",
      isExternalMenu: true,
    },
    {
      title: "CPA - Títulos Vencidos",
      moduleSlug: "financeiro_relatorios",
      path: "javascript:getFinancialOverdueTitles();",
      isExternalMenu: true,
    },
    {
      title: "CPA - Títulos Pagos",
      moduleSlug: "financeiro_relatorios",
      path: "javascript:getFinancialPaidTitles();",
      isExternalMenu: true,
    },
    {
      title: "CRE - Títulos em Aberto",
      moduleSlug: "financeiro_relatorios",
      path: "javascript:getFinancialReceivableTitles();",
      isExternalMenu: true,
    },
    {
      title: "CRE - Títulos Vencidos",
      moduleSlug: "financeiro_relatorios",
      path: "javascript:getFinancialReceiptOverdueTitles();",
      isExternalMenu: true,
    },
    {
      title: "CRE - Títulos Recebidos",
      moduleSlug: "financeiro_relatorios",
      path: "javascript:getFinancialReceiptTitles();",
      isExternalMenu: true,
    },
    {
      title: "Despesas por Centro de Custo",
      moduleSlug: "financeiro_relatorios",
      path: "javascript:search_cost_centers_analysis();",
      isExternalMenu: true,
    },
    {
      title: "CRE - Impressão Carnê",
      moduleSlug: "financeiro_relatorios",
      path: "printing_booklets",
      isExternalMenu: true,
    },
    {
      title: "Nat Fin Evolução",
      moduleSlug: "financeiro_analises",
      path: "financers_nature_evolution",
      isExternalMenu: true,
    },
    {
      title: "Nat Fin - Comparativo",
      moduleSlug: "financeiro_analises",
      path: "financers_nature_comparative",
      isExternalMenu: true,
    },
    {
      title: "CPA - Gerencial",
      moduleSlug: "financeiro_analises",
      path: "financial_payable_title_analysis",
      isExternalMenu: true,
    },
    {
      title: "CPA - Listagem",
      moduleSlug: "financeiro_analises",
      path: "financial_payable_title_consults",
      isExternalMenu: true,
    },
    {
      title: "CPA - Pagamentos",
      moduleSlug: "financeiro_analises",
      path: "financial_consults_paid_titles",
      isExternalMenu: true,
    },
    {
      title: "Ranking de Fornecedores",
      moduleSlug: "financeiro_analises",
      path: "financial_supplier_ranking_analysis",
      isExternalMenu: true,
    },
    {
      title: "CRE - Gerencial",
      moduleSlug: "financeiro_analises",
      path: "financial_receivable_title_analysis",
      isExternalMenu: true,
    },
    {
      title: "CRE - Recebimentos",
      moduleSlug: "financeiro_analises",
      path: "financial_consults_receipt_titles",
      isExternalMenu: true,
    },
    {
      title: "CRE - Renegociações",
      moduleSlug: "financeiro_analises",
      path: "financial_renegotiation_analysis",
      isExternalMenu: true,
    },
    {
      title: "CRE - Inadimplência",
      moduleSlug: "financeiro_analises",
      path: "financial_receivable_delinquency_analysis",
      isExternalMenu: true,
    },
    {
      title: "CRE - Listagem",
      moduleSlug: "financeiro_analises",
      path: "financial_receivable_title_consults",
      isExternalMenu: true,
    },
    {
      title: "Ranking de Clientes",
      moduleSlug: "financeiro_analises",
      path: "financial_client_ranking_analysis",
      isExternalMenu: true,
    },
    {
      title: "Antecipação Cliente/Fornecedor",
      moduleSlug: "financeiro_analises",
      path: "financial_advance_posting_analysis",
      isExternalMenu: true,
    },
    {
      title: "Limite de Crédito",
      moduleSlug: "financeiro_recursos",
      path: "credit_limits",
      isExternalMenu: true,
    },
    {
      title: "Liberação de Recurso",
      moduleSlug: "financeiro_recursos",
      path: "release_requests",
      isExternalMenu: true,
    },
    {
      title: "Prestação de Contas",
      moduleSlug: "financeiro_recursos",
      path: "rendering_accounts",
      isExternalMenu: true,
    },
    {
      title: "Acerto de Recurso",
      moduleSlug: "financeiro_recursos",
      path: "resource_adjustments",
      isExternalMenu: true,
    },
    {
      title: "Antecipação Cliente/Fornecedor",
      moduleSlug: "financeiro_recursos",
      path: "financial_advance_postings",
      isExternalMenu: true,
    },
    {
      title: "Manut. Registro Contábil",
      moduleSlug: "financeiro_utilitarios",
      path: "maintaining_accounting_records",
      isExternalMenu: true,
    },
    {
      title: "Geração Arquivo Terc. - Prosoft",
      moduleSlug: "financeiro_utilitarios",
      path: "financial_export_third",
      isExternalMenu: true,
    },
    {
      title: "Download Arquivo Terc. - Prosoft",
      moduleSlug: "financeiro_utilitarios",
      path: "financial_export_third_files",
      isExternalMenu: true,
    },
    {
      title: "CPA - Exclusão Pagamentos",
      moduleSlug: "financeiro_utilitarios",
      path: "financial_delete_paid_titles",
      isExternalMenu: true,
    },
    {
      title: "CRE - Exclusão Recebimentos",
      moduleSlug: "financeiro_utilitarios",
      path: "financial_delete_receipt_titles",
      isExternalMenu: true,
    },
    {
      title: "Manutenção Lançamentos",
      moduleSlug: "financeiro_utilitarios",
      path: "financial_posting_maintenance",
      isExternalMenu: true,
    },
    {
      title: "Pesquisa Eventos - CRE",
      moduleSlug: "financeiro_utilitarios",
      path: "financial_receivable_title_search",
      isExternalMenu: true,
    },
    {
      title: "Manutenção Títulos a Receber",
      moduleSlug: "financeiro_utilitarios",
      path: "dashboard_maintenance_in_lot",
      isExternalMenu: true,
    },
    {
      title: "Oportunidade - Tipos",
      moduleSlug: "crm_cadastros",
      path: "crm_opportunity_types",
      isExternalMenu: true,
    },
    {
      title: "Oportunidade - Fases",
      moduleSlug: "crm_cadastros",
      path: "crm_opportunity_stages",
      isExternalMenu: true,
    },
    {
      title: "Motivo Ganho/Perda",
      moduleSlug: "crm_cadastros",
      path: "crm_opportunity_reasons",
      isExternalMenu: true,
    },
    {
      title: "Tipo de Campanha",
      moduleSlug: "crm_cadastros",
      path: "crm_campaign_types",
      isExternalMenu: true,
    },
    {
      title: "Motivos de Contato",
      moduleSlug: "crm_cadastros",
      path: "crm_motives",
      isExternalMenu: true,
    },
    {
      title: "Motivos de Descarte",
      moduleSlug: "crm_cadastros",
      path: "crm_discart_motives",
      isExternalMenu: true,
    },
    {
      title: "Formas de Contato",
      moduleSlug: "crm_cadastros",
      path: "crm_forms",
      isExternalMenu: true,
    },
    {
      title: "Origens de Contato",
      moduleSlug: "crm_cadastros",
      path: "crm_contact_origins",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Gerente",
      moduleSlug: "crm_operacoes",
      path: "crm_company_dashboard",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Vendedor",
      moduleSlug: "crm_operacoes",
      path: "crm_personal_dashboard",
      isExternalMenu: true,
    },
    {
      title: "Campanhas",
      moduleSlug: "crm_operacoes",
      path: "crm_campaigns",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Parâmetros da Venda",
      moduleSlug: "crm_operacoes",
      path: "dashboard_sale_parameters",
      isExternalMenu: true,
    },
    {
      title: "Oportunidades Sintético",
      moduleSlug: "crm_relatorios",
      path: "javascript:getCrmAnalysisOportunities();",
      isExternalMenu: true,
    },
    {
      title: "Oportunidades Analítico",
      moduleSlug: "crm_relatorios",
      path: "javascript:getCrmAnalysisOportunitiesAnalytical();",
      isExternalMenu: true,
    },
    {
      title: "Clientes por Segmentação",
      moduleSlug: "crm_relatorios",
      path: "javascript:clientSegmentations();",
      isExternalMenu: true,
    },
    {
      title: "Pessoas - Listagem",
      moduleSlug: "crm_relatorios",
      path: "javascript:getCrmAnalysisPeople();",
      isExternalMenu: true,
    },
    {
      title: "Pessoas - por Proprietário",
      moduleSlug: "crm_relatorios",
      path: "javascript:getCrmAnalysisPeopleCrm();",
      isExternalMenu: true,
    },
    {
      title: "Oportunidades - em Aberto",
      moduleSlug: "crm_analises",
      path: "crm_active_opportunity",
      isExternalMenu: true,
    },
    {
      title: "Oportunidades - Fechadas",
      moduleSlug: "crm_analises",
      path: "crm_closed_opportunity",
      isExternalMenu: true,
    },
    {
      title: "Escolaridades",
      moduleSlug: "pessoas_cadastros",
      path: "individuals/individual_educations",
      isExternalMenu: true,
    },
    {
      title: "Especialidades",
      moduleSlug: "pessoas_cadastros",
      path: "individuals/individual_specializations",
      isExternalMenu: true,
    },
    {
      title: "Experiências",
      moduleSlug: "pessoas_cadastros",
      path: "individuals/individual_experiences",
      isExternalMenu: true,
    },
    {
      title: "Competências",
      moduleSlug: "pessoas_cadastros",
      path: "individuals/individual_competences",
      isExternalMenu: true,
    },
    {
      title: "Formulário Dinâmico",
      moduleSlug: "pessoas_cadastros",
      path: "individuals/individual_forms",
      isExternalMenu: true,
    },
    {
      title: "Escala para Avaliação",
      moduleSlug: "pessoas_cadastros",
      path: "individuals/individual_evaluation_metrics",
      isExternalMenu: true,
    },
    {
      title: "Perfis de Avaliação",
      moduleSlug: "pessoas_cadastros",
      path: "individuals/individual_evaluation_profiles",
      isExternalMenu: true,
    },
    {
      title: "Currículos - Status",
      moduleSlug: "pessoas_cadastros",
      path: "individuals/individual_status",
      isExternalMenu: true,
    },
    {
      title: "Mapeamento Competências",
      moduleSlug: "pessoas_operacoes",
      path: "individuals/individual_mapping_competences",
      isExternalMenu: true,
    },
    {
      title: "Dashboard Operacional",
      moduleSlug: "pessoas_operacoes",
      path: "individuals/PeopleDashboard/",
      isExternalMenu: true,
    },
    {
      title: "Perfil da Pessoa",
      moduleSlug: "pessoas_operacoes",
      path: "individuals/person_informations",
      isExternalMenu: true,
    },
    {
      title: "Processos de Avaliação",
      moduleSlug: "pessoas_operacoes",
      path: "individuals/individual_evaluation_processes",
      isExternalMenu: true,
    },
    {
      title: "Apontamentos",
      moduleSlug: "pessoas_operacoes",
      path: "individuals/individual_person_notes",
      isExternalMenu: true,
    },
    {
      title: "Planos de Desenvolvimento",
      moduleSlug: "pessoas_operacoes",
      path: "individuals/empowering_people",
      isExternalMenu: true,
    },
    {
      title: "Banco de Currículos",
      moduleSlug: "pessoas_operacoes",
      path: "individuals/curriculum",
      isExternalMenu: true,
    },
    {
      title: "Perfil da Pessoa",
      moduleSlug: "pessoas_analises",
      path: "individuals/person_information_analysis",
      isExternalMenu: true,
    },
    {
      title: "Apontamentos",
      moduleSlug: "pessoas_analises",
      path: "individuals/individual_person_notes/all",
      isExternalMenu: true,
    },
    {
      title: "Performance",
      moduleSlug: "pessoas_analises",
      path: "individuals/individual_analysis",
      isExternalMenu: true,
    },
    {
      title: "Planos de Desenvolvimento",
      moduleSlug: "pessoas_analises",
      path: "individuals/empowering_analysis",
      isExternalMenu: true,
    },
    {
      title: "Talentos",
      moduleSlug: "pessoas_analises",
      path: "individuals/person_informations/person_analysis",
      isExternalMenu: true,
    },
    {
      title: "Feedbacks",
      moduleSlug: "pessoas_analises",
      path: "individuals/individual_feedbacks",
      isExternalMenu: true,
    },
    {
      title: "Tipos de Objetos",
      moduleSlug: "materiais_cadastros",
      path: "patrimony_types",
      isExternalMenu: true,
    },
    {
      title: "Modelos de Objetos",
      moduleSlug: "materiais_cadastros",
      path: "patrimony_models",
      isExternalMenu: true,
    },
    {
      title: "Objetos - Fabricantes",
      moduleSlug: "materiais_cadastros",
      path: "manufacturers",
      isExternalMenu: true,
    },
    {
      title: "Veículos",
      moduleSlug: "materiais_cadastros",
      path: "vehicles/vehicles",
      isExternalMenu: true,
    },
    {
      title: "Kits",
      moduleSlug: "materiais_cadastros",
      path: "service_kits",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Gerencial",
      moduleSlug: "materiais_operacoes",
      path: "materials/manager_dashboard",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Operacional",
      moduleSlug: "materiais_operacoes",
      path: "materials/operational_dashboard",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Veículos",
      moduleSlug: "materiais_operacoes",
      path: "vehicles/transactions",
      isExternalMenu: true,
    },
    {
      title: "Pedido de Compra",
      moduleSlug: "materiais_operacoes",
      path: "materials/product_acquisition_requests",
      isExternalMenu: true,
    },
    {
      title: "Lcto NF Compra - Produto",
      moduleSlug: "materiais_operacoes",
      path: "invoice_entry_documents",
      isExternalMenu: true,
    },
    {
      title: "Lcto NF Compra - Serviço",
      moduleSlug: "materiais_operacoes",
      path: "materials/service_entry_documents",
      isExternalMenu: true,
    },
    {
      title: "Pedido de Venda - Inclusão",
      moduleSlug: "materiais_operacoes",
      path: "sale_orders",
      isExternalMenu: true,
    },
    {
      title: "Pedido de Venda - Faturamento",
      moduleSlug: "materiais_operacoes",
      path: "sale_order_billings",
      isExternalMenu: true,
    },
    {
      title: "NF Entrada - Aceitar Retorno",
      moduleSlug: "materiais_operacoes",
      path: "materials/client_documents_return",
      isExternalMenu: true,
    },
    {
      title: "Objetos - Movimentação Interna",
      moduleSlug: "materiais_operacoes",
      path: "materials/internal_patrimony_movimentations",
      isExternalMenu: true,
    },
    {
      title: "Objetos - Movimentação Externa",
      moduleSlug: "materiais_operacoes",
      path: "patrimony_client_movimentations",
      isExternalMenu: true,
    },
    {
      title: "Objetos - Outras Operações",
      moduleSlug: "materiais_operacoes",
      path: "materials/patrimony_movimentations",
      isExternalMenu: true,
    },
    {
      title: "Emissão NF Complementar",
      moduleSlug: "materiais_operacoes",
      path: "materials/icms_refunds",
      isExternalMenu: true,
    },
    {
      title: "Emissão de Notas Fiscais",
      moduleSlug: "materiais_operacoes",
      path: "product_invoice_notes",
      isExternalMenu: true,
    },
    {
      title: "NF Transferência - Entrada",
      moduleSlug: "materiais_operacoes",
      path: "transfer_invoice_notes",
      isExternalMenu: true,
    },
    {
      title: "Romaneio de Entregas",
      moduleSlug: "materiais_operacoes",
      path: "materials/invoice_notes_routes",
      isExternalMenu: true,
    },
    {
      title: "Fechamento de Estoque",
      moduleSlug: "materiais_operacoes",
      path: "product_closing_balance",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Operacional (Nova)",
      moduleSlug: "materiais_operacoes",
      path: "dashboard_operational_materials",
      isExternalMenu: true,
    },
    {
      title: "Gerar Inventário",
      moduleSlug: "materiais_operacoes",
      path: "inventory",
      isExternalMenu: true,
    },
    {
      title: "Realizar Contagem",
      moduleSlug: "materiais_operacoes",
      path: "counting_inventory",
      isExternalMenu: true,
    },
    {
      title: "Ficha de Movimentação",
      moduleSlug: "materiais_relatorios",
      path: "javascript:printMovimentation();",
      isExternalMenu: true,
    },
    {
      title: "Estoque - Inventário",
      moduleSlug: "materiais_relatorios",
      path: "javascript:inventory_analysis_filter();",
      isExternalMenu: true,
    },
    {
      title: "Catálogo de Preços",
      moduleSlug: "materiais_relatorios",
      path: "service_price_list_consults",
      isExternalMenu: true,
    },
    {
      title: "Materiais com Terceiros",
      moduleSlug: "materiais_relatorios",
      path: "javascript:modalMaterialsWithThird();",
      isExternalMenu: true,
    },
    {
      title: "Saldo Produto",
      moduleSlug: "materiais_analises",
      path: "materials/products_analysis_balances",
      isExternalMenu: true,
    },
    {
      title: "Saldo Produto - Por Local",
      moduleSlug: "materiais_analises",
      path: "materials/service_products_company_balances",
      isExternalMenu: true,
    },
    {
      title: "Giro de Estoque",
      moduleSlug: "materiais_analises",
      path: "materials/product_inventory_movimentations",
      isExternalMenu: true,
    },
    {
      title: "Estoque - Evolução",
      moduleSlug: "materiais_analises",
      path: "materials/stock_evolution_analysis",
      isExternalMenu: true,
    },
    {
      title: "CMV - Grupo X Produto",
      moduleSlug: "materiais_analises",
      path: "materials/mean_cost_sales",
      isExternalMenu: true,
    },
    {
      title: "Variação de Valores",
      moduleSlug: "materiais_analises",
      path: "materials/products_variation_values",
      isExternalMenu: true,
    },
    {
      title: "Pedidos de Venda - Geral",
      moduleSlug: "materiais_analises",
      path: "sale_request_analysis",
      isExternalMenu: true,
    },
    {
      title: "Pedidos Faturados - Gerencial",
      moduleSlug: "materiais_analises",
      path: "analysis_sale_request",
      isExternalMenu: true,
    },
    {
      title: "Materiais - Meu Estoque",
      moduleSlug: "materiais_analises",
      path: "materials/my_materials",
      isExternalMenu: true,
    },
    {
      title: "Materiais - Visão Geral",
      moduleSlug: "materiais_analises",
      path: "materials/materials_overview",
      isExternalMenu: true,
    },
    {
      title: "Produtos - Visão Geral",
      moduleSlug: "materiais_analises",
      path: "materials/product_overview",
      isExternalMenu: true,
    },
    {
      title: "Veículos",
      moduleSlug: "materiais_analises",
      path: "vehicles/analysis_vehicles",
      isExternalMenu: true,
    },
    {
      title: "Saldo Inicial",
      moduleSlug: "materiais_utilitarios",
      path: "service_product_opening_balance",
      isExternalMenu: true,
    },
    {
      title: "Reabertura de Estoque",
      moduleSlug: "materiais_utilitarios",
      path: "javascript:modalReopenStock();",
      isExternalMenu: true,
    },
    {
      title: "Cartas de Correção",
      moduleSlug: "materiais_utilitarios",
      path: "invoice_correction_letters",
      isExternalMenu: true,
    },
    {
      title: "Estoques Máx/Min - Alteração em Lote",
      moduleSlug: "materiais_utilitarios",
      path: "materials/UpdateStockValues",
      isExternalMenu: true,
    },
    {
      title: "Status de Conexão",
      moduleSlug: "isp_|_telecom_cadastros",
      path: "authentication_address_lists",
      isExternalMenu: true,
    },
    {
      title: "Banco de IP’s",
      moduleSlug: "isp_|_telecom_cadastros",
      path: "dashboard_authentication_ips",
      isExternalMenu: true,
    },
    {
      title: "Concentradores",
      moduleSlug: "isp_|_telecom_cadastros",
      path: "authentication_concentrators",
      isExternalMenu: true,
    },
    {
      title: "Grupos de IPs",
      moduleSlug: "isp_|_telecom_cadastros",
      path: "authentication_ip_groups",
      isExternalMenu: true,
    },
    {
      title: "Modelos de Scripts",
      moduleSlug: "isp_|_telecom_cadastros",
      path: "provisioning_scripts",
      isExternalMenu: true,
    },
    {
      title: "Pontos de Acesso",
      moduleSlug: "isp_|_telecom_cadastros",
      path: "authentication_access_points",
      isExternalMenu: true,
    },
    {
      title: "Sites",
      moduleSlug: "isp_|_telecom_cadastros",
      path: "authentication_sites",
      isExternalMenu: true,
    },
    {
      title: "Splitters",
      moduleSlug: "isp_|_telecom_cadastros",
      path: "authentication_splitters",
      isExternalMenu: true,
    },
    {
      title: "Visão Geral",
      moduleSlug: "isp_|_telecom_cadastros",
      path: "authentication_tree",
      isExternalMenu: true,
    },
    {
      title: "Caixas de Rede",
      moduleSlug: "isp_|_telecom_cadastros",
      path: "network_boxes",
      isExternalMenu: true,
    },
    {
      title: "Atributos",
      moduleSlug: "isp_|_telecom_cadastros",
      path: "authentication_attributes",
      isExternalMenu: true,
    },
    {
      title: "Layout de Atributos",
      moduleSlug: "isp_|_telecom_cadastros",
      path: "authentication_attributes_layouts",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Manutenção",
      moduleSlug: "isp_|_telecom_operacoes",
      path: "network_maintenances",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Auditoria Conexões",
      moduleSlug: "isp_|_telecom_operacoes",
      path: "authentication_concentrator_logs",
      isExternalMenu: true,
    },
    {
      title: "Telefonia - Listagem",
      moduleSlug: "isp_|_telecom_operacoes",
      path: "metallic_pair_phones",
      isExternalMenu: true,
    },
    {
      title: "Conexões - Listagem",
      moduleSlug: "isp_|_telecom_operacoes",
      path: "authentication_contract_connections",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - MaxiTV",
      moduleSlug: "isp_|_telecom_operacoes",
      path: "dashboard_maxi_tv",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Telefonia",
      moduleSlug: "isp_|_telecom_operacoes",
      path: "dashboard_telephony",
      isExternalMenu: true,
    },
    {
      title: "Lista de Conexões",
      moduleSlug: "isp_|_telecom_relatorios",
      path: "javascript:cpe_list_filter();",
      isExternalMenu: true,
    },
    {
      title: "Usuários On-line",
      moduleSlug: "isp_|_telecom_analises",
      path: "online_users",
      isExternalMenu: true,
    },
    {
      title: "PPPoE - Extrato por IP",
      moduleSlug: "isp_|_telecom_analises",
      path: "connection_extracts/extract_by_ip",
      isExternalMenu: true,
    },
    {
      title: "PPPoE - Extrato por Cliente",
      moduleSlug: "isp_|_telecom_analises",
      path: "connection_extracts",
      isExternalMenu: true,
    },
    {
      title: "Visão Geral",
      moduleSlug: "isp_|_telecom_analises",
      path: "network_analysis",
      isExternalMenu: true,
    },
    {
      title: "Conexões Excluídas",
      moduleSlug: "isp_|_telecom_utilitarios",
      path: "authentication_contract_connection_occurrences",
      isExternalMenu: true,
    },
    {
      title: "Índices de Reajuste",
      moduleSlug: "faturamento_cadastros",
      path: "adjustment_indices",
      isExternalMenu: true,
    },
    {
      title: "Produtos/Serviços",
      moduleSlug: "faturamento_cadastros",
      path: "service_products",
      isExternalMenu: true,
    },
    {
      title: "Grupo Produtos/Serviços",
      moduleSlug: "faturamento_cadastros",
      path: "service_product_groups",
      isExternalMenu: true,
    },
    {
      title: "Ciclos de Faturamento",
      moduleSlug: "faturamento_cadastros",
      path: "contract_date_managements",
      isExternalMenu: true,
    },
    {
      title: "Tipo de Contrato",
      moduleSlug: "faturamento_cadastros",
      path: "contract_types",
      isExternalMenu: true,
    },
    {
      title: "Operações",
      moduleSlug: "faturamento_cadastros",
      path: "financial_operations",
      isExternalMenu: true,
    },
    {
      title: "Modelo/Série de Documentos",
      moduleSlug: "faturamento_cadastros",
      path: "invoice_series",
      isExternalMenu: true,
    },
    {
      title: "CFOP",
      moduleSlug: "faturamento_cadastros",
      path: "tax_code_operations",
      isExternalMenu: true,
    },
    {
      title: "Evento Padrão",
      moduleSlug: "faturamento_cadastros",
      path: "contract_event_types",
      isExternalMenu: true,
    },
    {
      title: "Listas de Preços",
      moduleSlug: "faturamento_cadastros",
      path: "service_price_lists",
      isExternalMenu: true,
    },
    {
      title: "Tabela ICMS",
      moduleSlug: "faturamento_cadastros",
      path: "materials/service_product_icms_aliquots",
      isExternalMenu: true,
    },
    {
      title: "Tabela CEST",
      moduleSlug: "faturamento_cadastros",
      path: "service_product_cests",
      isExternalMenu: true,
    },
    {
      title: "Tipos de Faturamento Especial",
      moduleSlug: "faturamento_cadastros",
      path: "special_billing_types",
      isExternalMenu: true,
    },
    {
      title: "Configurações de Preço",
      moduleSlug: "faturamento_cadastros",
      path: "sale_price_configurations",
      isExternalMenu: true,
    },
    {
      title: "Valores Eventuais",
      moduleSlug: "faturamento_operacoes",
      path: "contract_eventual_values",
      isExternalMenu: true,
    },
    {
      title: "Pré-Nota",
      moduleSlug: "faturamento_operacoes",
      path: "provisional_invoice_notes",
      isExternalMenu: true,
    },
    {
      title: "Faturar Contrato - Simples",
      moduleSlug: "faturamento_operacoes",
      path: "billings",
      isExternalMenu: true,
    },
    {
      title: "Faturar Contratos - Mult. Operações",
      moduleSlug: "faturamento_operacoes",
      path: "multiple_billings",
      isExternalMenu: true,
    },
    {
      title: "Faturar Contratos - Cob. Antecipada",
      moduleSlug: "faturamento_operacoes",
      path: "anticipated_revenues",
      isExternalMenu: true,
    },
    {
      title: "Faturar Contratos - Cob. Individual",
      moduleSlug: "faturamento_operacoes",
      path: "anticipated_multiple_revenues",
      isExternalMenu: true,
    },
    {
      title: "Faturar Solicitações",
      moduleSlug: "faturamento_operacoes",
      path: "assignment_sale_orders",
      isExternalMenu: true,
    },
    {
      title: "Faturamento por Terceiros",
      moduleSlug: "faturamento_operacoes",
      path: "third_party_billings",
      isExternalMenu: true,
    },
    {
      title: "Telefonia - Processar Cobrança",
      moduleSlug: "faturamento_operacoes",
      path: "process_billing_telephony",
      isExternalMenu: true,
    },
    {
      title: "Telefonia - Retorno Cobrança",
      moduleSlug: "faturamento_operacoes",
      path: "generate_telephony_returns",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Faturamento",
      moduleSlug: "faturamento_operacoes",
      path: "billing/billing_operational_dashboard",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Faturamento (Nova)",
      moduleSlug: "faturamento_operacoes",
      path: "dashboard_billing",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Contratos (Nova)",
      moduleSlug: "faturamento_operacoes",
      path: "dashboard_contracts",
      isExternalMenu: true,
    },
    {
      title: "Contratos por Período",
      moduleSlug: "faturamento_relatorios",
      path: "javascript:contract_analysis();",
      isExternalMenu: true,
    },
    {
      title: "Contratos por Operação",
      moduleSlug: "faturamento_relatorios",
      path: "javascript:contract_analysis_billing();",
      isExternalMenu: true,
    },
    {
      title: "Faturamento por Local",
      moduleSlug: "faturamento_relatorios",
      path: "javascript:invoice_note_analysis();",
      isExternalMenu: true,
    },
    {
      title: "Faturamento por Grupo de Produto/Serviço",
      moduleSlug: "faturamento_relatorios",
      path: "javascript:invoice_group_service_analysis();",
      isExternalMenu: true,
    },
    {
      title: "Faturamento por Produto/Serviço",
      moduleSlug: "faturamento_relatorios",
      path: "javascript:invoice_item_service_analysis();",
      isExternalMenu: true,
    },
    {
      title: "Faturamento por Vendedor",
      moduleSlug: "faturamento_relatorios",
      path: "javascript:invoiceNoteVendorsReport();",
      isExternalMenu: true,
    },
    {
      title: "Faturamento por Região",
      moduleSlug: "faturamento_relatorios",
      path: "javascript:invoiceNoteRegionsReport();",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Gerencial",
      moduleSlug: "faturamento_analises",
      path: "invoice_gerencial_analysis",
      isExternalMenu: true,
    },
    {
      title: "Faturamento – Gerencial Analítico",
      moduleSlug: "faturamento_analises",
      path: "invoice_general_analysis",
      isExternalMenu: true,
    },
    {
      title: "Contratos - Gerencial",
      moduleSlug: "faturamento_analises",
      path: "contract_general_analysis",
      isExternalMenu: true,
    },
    {
      title: "Contratos - Rentabilidade",
      moduleSlug: "faturamento_analises",
      path: "contracts_profitability",
      isExternalMenu: true,
    },
    {
      title: "Contratos - Eventos",
      moduleSlug: "faturamento_analises",
      path: "contract_event_analysis",
      isExternalMenu: true,
    },
    {
      title: "Operações por Cliente",
      moduleSlug: "faturamento_analises",
      path: "service_people_consults",
      isExternalMenu: true,
    },
    {
      title: "Operações por Contrato",
      moduleSlug: "faturamento_analises",
      path: "contract_consults",
      isExternalMenu: true,
    },
    {
      title: "Indicadores do Faturamento",
      moduleSlug: "faturamento_analises",
      path: "authentication_indicators",
      isExternalMenu: true,
    },
    {
      title: "Contratos - Reativação",
      moduleSlug: "faturamento_utilitarios",
      path: "reactive_contracts",
      isExternalMenu: true,
    },
    {
      title: "Doc. Saída - Impressão Manual",
      moduleSlug: "faturamento_utilitarios",
      path: "fanfold_prints",
      isExternalMenu: true,
    },
    {
      title: "Doc. Saída - Impressão em Lote",
      moduleSlug: "faturamento_utilitarios",
      path: "invoice_notes_mult_print",
      isExternalMenu: true,
    },
    {
      title: "Doc. Saída - Efetivar",
      moduleSlug: "faturamento_utilitarios",
      path: "update_invoice_notes",
      isExternalMenu: true,
    },
    {
      title: "Documentos - Downloads",
      moduleSlug: "faturamento_utilitarios",
      path: "download_invoice_notes",
      isExternalMenu: true,
    },
    {
      title: "Dctos Emitidos - Manutenção",
      moduleSlug: "faturamento_utilitarios",
      path: "issued_invoice_note_maintenances",
      isExternalMenu: true,
    },
    {
      title: "Contratos - Manutenção em Lote",
      moduleSlug: "faturamento_utilitarios",
      path: "contract_bulk_edit",
      isExternalMenu: true,
    },
    {
      title: "Emissão NF - Cob Antecipada",
      moduleSlug: "faturamento_utilitarios",
      path: "generate_invoice_from_cre",
      isExternalMenu: true,
    },
    {
      title: "Impressão e Download",
      moduleSlug: "faturamento_utilitarios",
      path: "dashboard_batch_printing",
      isExternalMenu: true,
    },
    {
      title: "Lcto NF Manual",
      moduleSlug: "fiscal_operacoes",
      path: "sped/manual_invoice_notes",
      isExternalMenu: true,
    },
    {
      title: "Geração SPED Fiscal",
      moduleSlug: "fiscal_operacoes",
      path: "sped_analysis",
      isExternalMenu: true,
    },
    {
      title: "Geração SPED Contribuições",
      moduleSlug: "fiscal_operacoes",
      path: "sped_analysis_contributions",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Arquivos Magnéticos",
      moduleSlug: "fiscal_operacoes",
      path: "files_integrations",
      isExternalMenu: true,
    },
    {
      title: " Dashboard - Arquivos Magnéticos (Nova)",
      moduleSlug: "fiscal_operacoes",
      path: "new_files_integrations",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Menu Fiscal (SC)",
      moduleSlug: "fiscal_operacoes",
      path: "dashboard_fiscal_menu",
      isExternalMenu: true,
    },
    {
      title: "Listagem de Documentos",
      moduleSlug: "fiscal_relatorios",
      path: "javascript:openTaxationFilter();",
      isExternalMenu: true,
    },
    {
      title: "Manutenção NF Entrada",
      moduleSlug: "fiscal_utilitarios",
      path: "javascript:openInvoiceMaintenanceFilter();",
      isExternalMenu: true,
    },
    {
      title: "Formas de Contato",
      moduleSlug: "crm__voalle_cadastros",
      path: "contact_forms",
      isExternalMenu: true,
    },
    {
      title: "Motivos de Contato",
      moduleSlug: "crm__voalle_cadastros",
      path: "contact_motives",
      isExternalMenu: true,
    },
    {
      title: "Origens de Contato",
      moduleSlug: "crm__voalle_cadastros",
      path: "crm_contact_origins",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Gerente",
      moduleSlug: "crm__voalle_operacoes",
      path: "dashboard_manager",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Vendedor",
      moduleSlug: "crm__voalle_operacoes",
      path: "dashboard_seller",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Parâmetros do CRM",
      moduleSlug: "crm__voalle_operacoes",
      path: "dashboard_parameters",
      isExternalMenu: true,
    },
    {
      title: "Praças de Venda",
      moduleSlug: "crm__voalle_operacoes",
      path: "selling_places",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Consulta e Análise de Crédito",
      moduleSlug: "crm__voalle_operacoes",
      path: "dashboard_trust",
      isExternalMenu: true,
    },
    {
      title: "Financeiro/Comercial",
      moduleSlug: "business_intelligence_paineis_operacionais",
      path: "standard_dashboards",
      isExternalMenu: true,
    },
    {
      title: "Service Desk",
      moduleSlug: "business_intelligence_paineis_operacionais",
      path: "standard_dashboards/service_desk",
      isExternalMenu: true,
    },
    {
      title: "Clientes",
      moduleSlug: "business_intelligence_paineis_operacionais",
      path: "standard_dashboards/clients",
      isExternalMenu: true,
    },
    {
      title: "CRM",
      moduleSlug: "business_intelligence_paineis_gerenciais",
      path: "bi/dashboard/crm",
      isExternalMenu: true,
    },
    {
      title: "Service Desk",
      moduleSlug: "business_intelligence_paineis_gerenciais",
      path: "bi/dashboard/service_desk",
      isExternalMenu: true,
    },
    {
      title: "ISP | Telecom",
      moduleSlug: "business_intelligence_paineis_gerenciais",
      path: "bi/dashboard/isp",
      isExternalMenu: true,
    },
    {
      title: "Materiais",
      moduleSlug: "business_intelligence_paineis_gerenciais",
      path: "bi/dashboard/materials",
      isExternalMenu: true,
    },
    {
      title: "Faturamento",
      moduleSlug: "business_intelligence_paineis_gerenciais",
      path: "bi/dashboard/billing",
      isExternalMenu: true,
    },
    {
      title: "Financeiro",
      moduleSlug: "business_intelligence_paineis_gerenciais",
      path: "bi/dashboard/financial",
      isExternalMenu: true,
    },
    {
      title: "CRM",
      moduleSlug: "business_intelligence_paineis_avancados",
      path: "bi/advanced_dashboard/crm",
      isExternalMenu: true,
    },
    {
      title: "Service Desk",
      moduleSlug: "business_intelligence_paineis_avancados",
      path: "bi/advanced_dashboard/service_desk",
      isExternalMenu: true,
    },
    {
      title: "ISP | Telecom",
      moduleSlug: "business_intelligence_paineis_avancados",
      path: "bi/advanced_dashboard/isp",
      isExternalMenu: true,
    },
    {
      title: "Materiais",
      moduleSlug: "business_intelligence_paineis_avancados",
      path: "bi/advanced_dashboard/materials",
      isExternalMenu: true,
    },
    {
      title: "Faturamento",
      moduleSlug: "business_intelligence_paineis_avancados",
      path: "bi/advanced_dashboard/billing",
      isExternalMenu: true,
    },
    {
      title: "Financeiro",
      moduleSlug: "business_intelligence_paineis_avancados",
      path: "bi/advanced_dashboard/financial",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Materiais",
      moduleSlug: "unidades_de_negocio_operacoes",
      path: "company_place_business_units_movimentations",
      isExternalMenu: true,
    },
    {
      title: "Dashboard - Contratos",
      moduleSlug: "unidades_de_negocio_operacoes",
      path: "business_units_operational",
      isExternalMenu: true,
    },
    {
      title: "Conexões - Listagem",
      moduleSlug: "unidades_de_negocio_operacoes",
      path: "business_units_operational_connections",
      isExternalMenu: true,
    },
    {
      title: "Conexões - Provisionamento",
      moduleSlug: "unidades_de_negocio_operacoes",
      path: "business_units_provisioning",
      isExternalMenu: true,
    },
    {
      title: "Indicadores",
      moduleSlug: "unidades_de_negocio_analises",
      path: "business_units_indicators",
      isExternalMenu: true,
    },
    {
      title: "CRON Logs",
      moduleSlug: "manutencoes_suite",
      path: "company_cron_logs",
      isExternalMenu: true,
    },
    {
      title: "Fila de E-mails",
      moduleSlug: "manutencoes_suite",
      path: "queued_tasks",
      isExternalMenu: true,
    },
    {
      title: "Fila de Processamento",
      moduleSlug: "manutencoes_suite",
      path: "syn_queue",
      isExternalMenu: true,
    },
    {
      title: "Logs do Servidor",
      moduleSlug: "manutencoes_suite",
      path: "logs_view",
      isExternalMenu: true,
    },
    {
      title: "Agendador de Tarefas",
      moduleSlug: "manutencoes_suite",
      path: "schedule_tasks",
      isExternalMenu: true,
    },
    {
      title: "NF - Manutenções",
      moduleSlug: "manutencoes_faturamento",
      path: "invoice_maintenances",
      isExternalMenu: true,
    },
    {
      title: "CNAEs",
      moduleSlug: "manutencoes_faturamento",
      path: "company_place_cnae_auxiliares",
      isExternalMenu: true,
    },
    {
      title: "Manutenção Retornos",
      moduleSlug: "manutencoes_financeiro",
      path: "financial_remittance_return_maintenance",
      isExternalMenu: true,
    },
    {
      title: "Integração Watch Brasil",
      moduleSlug: "manutencoes_financeiro",
      path: "contract_items_maintenance",
      isExternalMenu: true,
    },
    {
      title: "Integradores",
      moduleSlug: "manutencoes_integracoes",
      path: "api_configs",
      isExternalMenu: true,
    },
    {
      title: "Log de Transações",
      moduleSlug: "manutencoes_integracoes",
      path: "integration_logs",
      isExternalMenu: true,
    },
    {
      title: "Visualizações das Filas",
      moduleSlug: "manutencoes_integracoes",
      path: "queue_data",
      isExternalMenu: true,
    },
    {
      title: "Integrações Webhooks",
      moduleSlug: "manutencoes_integracoes",
      path: "webhook_configs",
      isExternalMenu: true,
    },
    {
      title: "Webhook Data Storage",
      moduleSlug: "manutencoes_integracoes",
      path: "webhook_data_storage",
      isExternalMenu: true,
    },
    {
      title: "Insígnia",
      moduleSlug: "crm_cadastros",
      path: "crm/registrations?menuId=2#registrations",
      isExternalMenu: false,
    },
  ],
}

export const voaleStoreMock = [
  {
    title: "TECH",
    link: "#",
    img: "https://i.postimg.cc/1XdP7JL8/1x1-CRM-2.webp",
  },
  {
    title: "Finee",
    link: "#",
    img: "https://i.postimg.cc/8Cqrrmym/Property-1-Variant2.webp",
  },
  {
    title: "SyntesisIT",
    link: "#",
    img: "https://i.postimg.cc/kXq6P46w/412985634-1087771765527211-2254225067117320455-n.webp",
  },
  {
    title: "UPvalue",
    link: "#",
    img: "https://i.postimg.cc/1XdP7JL8/1x1-CRM-2.webp",
  },
  {
    title: "Universidade Voalle",
    link: "#",
    img: "https://i.postimg.cc/8Cqrrmym/Property-1-Variant2.webp",
  },
]
